# no of cores to use
N_JOBS = 2

# select features to combine
USE_SIFT = True
USE_RGB = False

# sift point types
SIFT_USE_DENSE_POINTS = True
SIFT_USE_HARRIS_POINTS = True
SIFT_USE_HESSIAN_POINTS = True

# sift point parameters
SIFT_DENSE_POINT_STRIDE = 25
SIFT_HARRIS_POINT_SIGMA = 1.0
SIFT_HARRIS_POINT_MAG_THRESHOLD = 15
SIFT_HARRIS_POINT_HES_THRESHOLD = 10
SIFT_HARRIS_POINT_NSM_NEIGHBORHOOD = 10
SIFT_HESSIAN_POINT_SIGMA = 1.0
SIFT_HESSIAN_POINT_MAG_THRESHOLD = 5
SIFT_HESSIAN_POINT_NSM_NEIGHBORHOOD = 10

# rgb features
RGB_PATCH_SIZE = (3, 3)

# code book generation
CODE_BOOK_KMEANS_CLUSTERS = 1000
CODE_BOOK_KMEANS_USE_MINI_BATCH = True
CODE_BOOK_DISTANCE = None

# histogram
HISTOGRAM_IS_BINARY = True

# k nearest neighbor classifier
CLASSIFIER_KNN_NEIGHBORS = 20
CLASSIFIER_KNN_WEIGHTS = 'uniform'
